# Generated by Django 5.1.1 on 2024-10-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yapsteruser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthdate'),
        ),
    ]
