# Generated by Django 5.1.1 on 2024-11-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_remove_yapsteruser_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('tries', models.IntegerField()),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_creator', to='user.yapsteruser')),
            ],
        ),
    ]
