# Generated by Django 5.1.1 on 2024-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlegame',
            name='tries',
            field=models.IntegerField(default=1),
        ),
    ]
