# Generated by Django 5.1.1 on 2024-11-27 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_yapsteruser_birthdate_and_more'),
        ('wordle', '0002_alter_wordlegame_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlegame',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordle_receiver', to='user.yapsteruser'),
        ),
    ]
