# Generated by Django 5.1.1 on 2024-11-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_wordlegame_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlegame',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
