# Generated by Django 5.1.1 on 2024-11-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_yapsteruser_birthdate_and_more'),
        ('wordle', '0004_alter_wordlegame_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlegame',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_creator', to='user.yapsteruser'),
        ),
        migrations.AlterField(
            model_name='wordlegame',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordle_receiver', to='user.yapsteruser'),
        ),
    ]
