# Generated by Django 5.1.1 on 2024-12-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0006_remove_wordlegame_receiver_wordlegame_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlegame',
            name='guesses',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
