# Generated by Django 5.1.1 on 2024-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_yapsteruser_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yapsteruser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
