# Generated by Django 5.1.1 on 2024-11-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_yapsteruser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='yapsteruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
