# Generated by Django 5.1.1 on 2024-11-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_yapsteruser_city_yapsteruser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yapsteruser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AlterField(
            model_name='yapsteruser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yapsteruser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yapsteruser',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='yapsteruser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
