# Generated by Django 5.1.1 on 2024-11-02 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('user', '0005_yapsteruser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_users', to='user.yapsteruser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocklist_user', to='user.yapsteruser')),
            ],
        ),
    ]
