# Generated by Django 5.1.1 on 2024-10-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatuser_member_alter_message_chat_belong_and_more'),
        ('user', '0003_yapsteruser_is_deleted_alter_yapsteruser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
