# Generated by Django 5.1.1 on 2024-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_chat_belong_chatuser_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=255),
        ),
    ]
