# Generated by Django 5.1.1 on 2024-11-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_chat_name'),
        ('user', '0008_yapsteruser_cover_photo_alter_yapsteruser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatuser', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.yapsteruser'),
        ),
    ]
