# Generated by Django 5.1.1 on 2024-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatuser_chat_alter_chatuser_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
