# Generated by Django 5.1.1 on 2024-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(max_length=255),
        ),
    ]
