# Generated by Django 5.1.1 on 2024-12-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chatuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_pm',
            field=models.BooleanField(default=True),
        ),
    ]
