# Generated by Django 5.1.2 on 2024-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_pm',
            field=models.BooleanField(default=False),
        ),
    ]
