# Generated by Django 5.1.1 on 2024-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuser',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateField(auto_now_add=True),
        ),
    ]
